services:

  # development services
  app-dev:
    container_name: nestjs-app-dev
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    env_file:
      - .env.development
    ports:
      - '3000:3000'
    volumes:
      - ./backend:/app
      - /app/node_modules

  backend:
    image: ghcr.io/malannly/film-backend:latest
    container_name: nestjs-app-prod
    env_file:
      - .env.production
    ports:
      - '3001:3000'

  # postgreSQL
  db:
    image: postgres:17-alpine
    restart: unless-stopped
    container_name: nestjs-db
    environment:
      POSTGRES_DB: prac
      POSTGRES_USER: prac
      POSTGRES_PASSWORD: 1234
    ports:
      - '5432:5432'
    volumes:
      - db-data:/var/lib/postgresql/data

  # pg admin service
  pgadmin:
    image: dpage/pgadmin4
    container_name: nestjs-pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=1234
    ports:
      - '8080:80'
    depends_on:
      - db

  frontend:
    image: ghcr.io/malannly/film-frontend:latest
    build:
      context: frontend
    environment:
      VITE_base_url: /
      VITE_API_URL: /api.afisha
      VITE_CND_URL: /content/afisha
    depends_on:
      - backend
    volumes:
      - frontend_build:/app/dist

volumes:
  db-data:
  frontend_build:
     
# services:
#   backend:
#     image: ghcr.io/malannly/film-backend:latest
#     container_name: backend
#     restart: unless-stopped
#     environment:
#       DATABASE_DRIVER: postgres
#       DATABASE_URL: postgres://prac:1234@db:5432/prac
#       DATABASE_USERNAME: prac
#       DATABASE_PASSWORD: 1234
#     ports:
#       - "3000:3000"
#     depends_on:
#       - db

#   frontend:
#     image: ghcr.io/malannly/film-frontend:latest
#     container_name: frontend
#     restart: unless-stopped
#     ports:
#       - "80:80"
#     depends_on:
#       - backend

#   db:
#     image: postgres:17-alpine
#     container_name: db
#     restart: unless-stopped
#     environment:
#       POSTGRES_DB: prac
#       POSTGRES_USER: prac
#       POSTGRES_PASSWORD: 1234
#     volumes:
#       - postgres_data:/var/lib/postgresql/data

#   pgadmin:
#     image: dpage/pgadmin4
#     container_name: pgadmin
#     restart: unless-stopped
#     environment:
#       PGADMIN_DEFAULT_EMAIL: admin@gmail.com
#       PGADMIN_DEFAULT_PASSWORD: 1234
#     ports:
#       - "8080:80"
#     depends_on:
#       - db

# volumes:
#   postgres_data: